version: "3"

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "redis_data:/bitnami/redis/data"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ".:/app"
    environment:
      - REDIS_HOST=redis:6379
    ports:
      - "1323:1323"

volumes:
  redis_data:
